### ISSUE TITLE
suggest a name da

### ISSUE THREAD

**Issue by bhargav191098** [Deepak-Ceg/sleep-stage-scorer-summer-intern-project-#1]

**Comment by Deepak-Ceg** [comment]
suggest a name then

**Comment by bhargav191098** [comment]
Definitely not terrible tensors for two reasons:
a) Its an official project and no kidding around
b) a.

**Comment by bhargav191098** [comment]
Sleep Stage Scorer - Summer Intern project.

**Comment by Deepak-Ceg** [comment]
sleep stage scorer nu potalae akara vanthuran

**Comment by bhargav191098** [comment]
Terrible Tensors has no relevance to the project da. Except for using Tensor Flow which is true  for any TF project.

**Comment by Deepak-Ceg** [comment]
fine
